Viewer/Models/Trait.cs
using System.ComponentModel.DataAnnotations;
using System;
using System.Collections.Generic;
using RestSharp;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Viewer.Models
{
    public class Trait
    {
        public int TraitId { get; set; }
        [Required]
        public string Name { get; set; }

        // Trait attributes
        [Required]
        [Range(-20, 20, ErrorMessage = "Stats go from 1 to 20.")]
        public int Might { get; set; }

        [Required]
        [Range(-20, 20, ErrorMessage = "Stats go from 1 to 20.")]
        public int Spryness { get; set; }

        [Required]
        [Range(-20, 20, ErrorMessage = "Stats go from 1 to 20.")]
        public int Judgement { get; set; }

        [Required]
        [Range(-20, 20, ErrorMessage = "Stats go from 1 to 20.")]
        public int Echo { get; set; }

        [Required]
        [Range(-20, 20, ErrorMessage = "Stats go from 1 to 20.")]
        public int Magnetism { get; set; }

        [Required]
        [Range(-20, 20, ErrorMessage = "Stats go from 1 to 20.")]
        public int Fortune { get; set; }
        public virtual ICollection<CharacterTrait> Characters { get; }

        //Stretch
        // public List<Delegate> Contextuals;
        public Trait()
        {
            this.Characters = new HashSet<CharacterTrait>();
        }

        public static List<Trait> GetTraits()
        {
            var apiCallTask = TraitApiHelper.GetAll();
            var result = apiCallTask.Result;

            JArray jsonResponse = JsonConvert.DeserializeObject<JArray>(result);
            List<Trait> traitList = JsonConvert.DeserializeObject<List<Trait>>(jsonResponse.ToString());

            return traitList;
        }

        public static Trait GetDetails(int id)
        {
            var apiCallTask = TraitApiHelper.Get(id);
            var result = apiCallTask.Result;

            JObject jsonResponse = JsonConvert.DeserializeObject<JObject>(result);
            Trait trait = JsonConvert.DeserializeObject<Trait>(jsonResponse.ToString());
            return trait;
        }

        public static void Post(Trait trait)
        {
            string jsonTrait = JsonConvert.SerializeObject(trait);
            var apiCallTask = TraitApiHelper.Post(jsonTrait);
        }

        public static void Put(Trait trait)
        {
            string jsonTrait = JsonConvert.SerializeObject(trait);
            var apiCallTask = TraitApiHelper.Put(trait.TraitId, jsonTrait);
        }

        public static void Delete(int id)
        {
            var apiCallTask = TraitApiHelper.Delete(id);
        }
    }
}

Viewer/Controllers/TraitsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using Viewer.Models;

namespace Viewer.Controllers
{
    public class TraitsController : Controller
    {
        private readonly ViewerContext _db;

        public TraitsController(ViewerContext db)
        {
            _db = db;
        }

        public IActionResult Index(int page, int pageCount)
        {   
            IQueryable<Object> traitQuery = Trait.GetTraits().AsQueryable();
            if(page == 0 ){
               page = 1;
            }
            ViewBag.pageCount = pageCount;
            ViewBag.page = page;
            traitQuery = PaginationHelper.GetPaged(traitQuery, page, pageCount);
            List<Trait> results = traitQuery.Cast<Trait>().ToList();
            return View(results);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Trait trait)
        {
            _db.Traits.Add(trait);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Details(int id)
        {
            var thisTrait = _db.Traits
                .Include(trait => trait.Characters)
                .ThenInclude(join => join.Character)
                .FirstOrDefault(Trait => Trait.TraitId == id);
            return View(thisTrait);
        }

        public ActionResult Edit(int id)
        {
            var thisTrait = _db.Traits.FirstOrDefault(trait => trait.TraitId == id);
            return View(thisTrait);
        }

        [HttpPost]
        public ActionResult Edit(Trait trait)
        {
            _db.Entry(trait).State = EntityState.Modified;
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            var thisTrait = _db.Traits.FirstOrDefault(trait => trait.TraitId == id);
            return View(thisTrait);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            var thisTrait = _db.Traits.FirstOrDefault(trait => trait.TraitId == id);
            _db.Traits.Remove(thisTrait);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Viewer/Views/Traits/Create.cshtml
@{
  Layout = "_Layout";
}

@model Viewer.Models.Trait

<div>

  <div class='entryLabel'>
    <h4>Add a new Trait</h4>
  </div>
  <div class='entry'>

    @using (Html.BeginForm())
    {
      @Html.LabelFor(model => model.Name)
      @Html.TextBoxFor(model => model.Name, new{@required = "required"})
      @Html.LabelFor(model=>model.Might)
      @Html.EditorFor(model=>model.Might)
      @Html.LabelFor(model=>model.Spryness)
      @Html.EditorFor(model=>model.Spryness)
      @Html.LabelFor(model=>model.Judgement)
      @Html.EditorFor(model=>model.Judgement)
      @Html.LabelFor(model=>model.Echo)
      @Html.EditorFor(model=>model.Echo)
      @Html.LabelFor(model=>model.Magnetism)
      @Html.EditorFor(model=>model.Magnetism)
      @Html.LabelFor(model=>model.Fortune)
      @Html.EditorFor(model=>model.Fortune)
      <input type="submit" value="Add new Trait"/>
    }
  </div>
</div>
<p>@Html.ActionLink("Show all Traits", "Index")</p>

Viewer/Views/Traits/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Viewer.Models.Trait
<div>
  <div class='entryLabel'>
    <h2>
      Delete
    </h2>
  </div>
  <div class="entry">
    <h2>
      Are you sure you want to delete this?
    </h2>
    @Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
    @using (Html.BeginForm())
    {
      <input type="submit" value="Delete" />
    }
  </div>
</div>

Viewer/Views/Traits/Details.cshtml
@{
  Layout = "_Layout";
}

@model Viewer.Models.Trait;

<div class='jumbotron'>
  <h2>Trait Details</h2>
</div>

<div class="">
  <div class='entryLabel'>
    <h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>
  </div>
        @Html.LabelFor(model => model.Name)
        @Html.ValueFor(model=>model.Name)
  <table>
      <tr>
          <td style="border:1px solid black">@Html.LabelFor(model=>model.Might)</td>
          <td style="border:1px solid black">@Html.LabelFor(model=>model.Spryness)</td>
          <td style="border:1px solid black">@Html.LabelFor(model=>model.Judgement)</td>
          <td style="border:1px solid black">@Html.LabelFor(model=>model.Echo)</td>
          <td style="border:1px solid black">@Html.LabelFor(model=>model.Magnetism)</td>
          <td style="border:1px solid black">@Html.LabelFor(model=>model.Fortune)</td>
      </tr>
      <tr>
        <td style="border:1px solid black">@Html.ValueFor(model=>model.Might)</td>
        <td style="border:1px solid black">@Html.ValueFor(model=>model.Spryness)</td>
        <td style="border:1px solid black">@Html.ValueFor(model=>model.Judgement)</td>
        <td style="border:1px solid black">@Html.ValueFor(model=>model.Echo)</td>
        <td style="border:1px solid black">@Html.ValueFor(model=>model.Magnetism)</td>
        <td style="border:1px solid black">@Html.ValueFor(model=>model.Fortune)</td>
      </tr>
  </table>
  <div class=' entry'>
    <hr />
    @if(@Model.Characters.Count == 0)
    {
      <p>This Trait is not used yet :(</p>
    }
    else
    {
      <h4>Characters with this trait:</h4>
      <ul>
        @foreach(var join in Model.Characters)
        {
          <li>@Html.ActionLink($"{join.Character.Name}", "Details", "Characters", new {id=join.CharacterId})</li>
          <li>@Html.ActionLink($"{join.Character.Might}", "Details", "Characters", new {id=join.CharacterId})</li>
          <li>@Html.ActionLink($"{join.Character.Spryness}", "Details", "Characters", new {id=join.CharacterId})</li>
          <li>@Html.ActionLink($"{join.Character.Judgement}", "Details", "Characters", new {id=join.CharacterId})</li>
          <li>@Html.ActionLink($"{join.Character.Echo}", "Details", "Characters", new {id=join.CharacterId})</li>
          <li>@Html.ActionLink($"{join.Character.Magnetism}", "Details", "Characters", new {id=join.CharacterId})</li>
          <li>@Html.ActionLink($"{join.Character.Fortune}", "Details", "Characters", new {id=join.CharacterId})</li>
          <li>@Html.ActionLink($"{join.Character.Bio}", "Details", "Characters", new {id=join.CharacterId})</li>
          <li>@Html.ActionLink($"{join.Character.Name}", "Details", "Characters", new {id=join.CharacterId})</li>
        }
      </ul>
    }
  </div>
</div>
  @if(User.Identity.IsAuthenticated)
  {
    <div class='entryLabel propertyLabel'>
      Trait Links
    </div>

    <div class='property'>
      <p>@Html.ActionLink("Back to Traits", "Index")</p>
      <p>@Html.ActionLink("Edit Trait", "Edit", new { id = Model.TraitId })</p>
      <p>@Html.ActionLink("Delete Trait", "Delete", new { id = Model.TraitId })</p>
    </div>
  }
</div>

Viewer/Views/Traits/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Viewer.Models.Trait

<div>
  <div class='entryLabel'>
    <h2>Edit this Trait: @Html.DisplayFor(model => model.Name)
    </h2>
  </div>
  <div class='entry'>

    @using (Html.BeginForm())
    {
      @Html.HiddenFor(model => model.TraitId)
      @Html.LabelFor(model => model.Name)
      @Html.EditorFor(model => model.Name, new{htmlAttributes = new{  @required = "required"}})
      <input type="submit" value="Save" />
    }

  </div>
</div>

Viewer/Views/Traits/Index.cshtml
@{
  Layout = "_Layout";
}

@using Viewer.Models;
@model List<Viewer.Models.Trait>;

<div class='jumbotron'>
 <h1>Traits</h1>
</div>
<div>
  <div class='entryLabel'>
    <h2>
      Index
    </h2> 
  </div>
  <div class='entry'>
    @if (@Model.Count == 0)
    {
      <h3>No Traits have been added yet!</h3>
    } 

    @foreach (Trait Trait in Model)
    {
      <li>@Html.ActionLink($"{Trait.Name}", "Details", new { id = Trait.TraitId })</li>
    }
    
    @if(User.Identity.IsAuthenticated)
    {
      <p>@Html.ActionLink("Add new Trait", "Create")</p>
    }
        <li>Page: @ViewBag.page</li>
         <p>@Html.ActionLink("Back a Page", "Index", "Traits", new{page = ViewBag.page - 1})</p>
         
         <p>@Html.ActionLink("1", "Index", "Traits", new{page = ViewBag.page, pageCount = 1 })</p>
         
         <p>@Html.ActionLink("2", "Index", "Traits", new{page = ViewBag.page, pageCount = 2})</p>
         
         <p>@Html.ActionLink("3", "Index", "Traits", new{page = ViewBag.page, pageCount = 3})</p>
         <p>@Html.ActionLink("Next Page", "Index", "Traits", new{page = ViewBag.page + 1})</p>
  </div>
</div>